# file: chruby/tasks/chruby.yml

- file: path=/opt/build state=directory mode=0755 owner=root group=root

- stat: path="/opt/build"
  register: opt_build_created

- get_url: url=https://github.com/postmodern/chruby/archive/v{{chruby_chruby_version}}.tar.gz
           dest=/opt/build/chruby-{{chruby_chruby_version}}.tar.gz
           sha256sum={{chruby_chruby_checksum}}
  when: opt_build_created.stat.exists

- unarchive: src=/opt/build/chruby-{{chruby_chruby_version}}.tar.gz
             dest=/opt/build/
             copy=no
  register: chruby_unarchive

- shell: make install chdir=/opt/build/chruby-{{chruby_chruby_version}}
  when: chruby_unarchive.changed

- stat: path="{{chruby_chruby_exec_command}}"
  register: chruby_file
